name:                omocha
version:             0.1.1.0
synopsis:            Initial project template from stack
description:         Please see README.md
homepage:            http://github.com/name/project
license:             BSD3
license-file:        LICENSE
author:              gg
maintainer:          ggkuron@gmail.com
# copyright:           
category:            Game
build-type:          Simple
default-extensions: Strict StrictData
data-files: 
- ./static/images/*.png
- ./static/images/maptips/*.png

dependencies:
- base >= 4.9.1.0
executables:
  omocha:
    source-dirs:      .
    main:             Main.hs
    dependencies:       
    - omocha
    - GPipe >= 2.2.3
    - GPipe-GLFW
    - elerea
    - JuicyPixels
    - JuicyPixels-util
    - template-haskell
    - lens
    - linear
    - transformers
    - exception-transformers
    - containers
    - async
    ghc-options:         
    - -fprint-potential-instances
    - -Wall
library:
    exposed-modules: 
    - Paths_omocha
    - Omocha.Bitmap
    - Omocha.Class
    - Omocha.Font
    - Omocha.Internal.Finalizer
    - Omocha.Scene
    - Omocha.Collada
    source-dirs:     src
    dependencies:
    - either
    - GPipe >= 2.2.3
    - JuicyPixels
    - JuicyPixels-util
    - filepath
    - template-haskell
    - raw-strings-qq
    - directory
    - lens
    - freetype2 >= 0.1
    - containers
    - boundingboxes
    - linear
    - mtl >= 2.2
    - vector
    - random
    - HaXml
    - hxt
    - array
    - transformers
    - exception-transformers


tests:
    omocha-test:
        main:           Spec.hs
        source-dirs:    test/Omocha
        dependencies:
        - omocha 
        - hspec
        - raw-strings-qq
        - GPipe >= 2.2.3
        - vector

